### ISSUE TITLE
Armstrong dropdown fix

### ISSUE THREAD

**Issue by harryhartley** [Rocketmakers/armstrong-edge#115]
## Overview

I want to work around a bug in Armstrong which incorrectly displays calendar dropdowns

## Bug report (delete if not a bug report)

Projects using iOS calendar dropdown should use native device calendar inputs instead of Dropdown

### Subtasks

- [ ] CalendarInput should use native device calendar inputs instead of Dropdown
- [ ] Dropdown should be deprecated
- [ ] Unit Tests
- [ ] Storybook

### Notes

"I’ve had a look into this and it looks like the correct-er solution is to deprecate CalendarInput in favour of NativeDateInput (and probably also deprecate Dropdown) and then make sure that deprecation is followed through on projects. This means there’s not directly work to do exactly on this ticket, but we need to do some work re: Armstrong product management."

**Comment by tomRocketmakers** [comment]
Calendar component is being rewritten. As such, closing.
