### ISSUE TITLE
Add code examples to stories

### ISSUE THREAD

**Issue by adam-cove** [Rocketmakers/armstrong-edge#200]
## Overview

Storybook should have code examples

## Bug report 

MDX plugin is now SB7 compatible so we can add these back in

**Comment by jlews** [comment]
I'm not sure I understand this one. We already have MDX docs for the hooks, form elements, dialogs and other complex features, and we have the "show code" button for code examples on all of our standard components.

Is there something I'm missing?

**Comment by adamiprinciples** [comment]
ignore this, was clowning
