### ISSUE TITLE
Bound Input of type Number doesn't allow trailing zeros

### ISSUE THREAD

**Issue by adamiprinciples** [Rocketmakers/armstrong-edge#221]
## Bug report
Bound Input of type Number doesn't allow trailing zeros

### Expected Behaviour
Should let me enter a value like 1.0404

### Actual Behaviour
The second zero cannot be entered

### Steps to Reproduce
Add input of type number, try to enter 1.0405

**Comment by jlews** [comment]
Solved by:
https://github.com/Rocketmakers/armstrong-edge/pull/236

**Comment by jlews** [comment]
Solve by: https://github.com/Rocketmakers/armstrong-edge/pull/236
