### ISSUE TITLE
Calendar icon image on click does not open the calendar

### ISSUE THREAD

**Issue by marcusbowyer** [Rocketmakers/armstrong-edge#231]
## Bug report
When clicking on the calendar icon the calendar does not open.

Both on right overlay and left overlay.

### Expected Behaviour
When clicking on either overlay the icon the calendar opens.

### Actual Behaviour
When clicking on either overlay the icon the calendar does not open.

## Internal

We use JIRA for issue tracking internally. If you're in Rocketmakers and you have an issue to raise, raise a ticket in [JIRA](https://rocketmakers.atlassian.net/jira/software/projects/ARM/boards/154) and notify the `#armstrong` Slack channel.

**Comment by jlews** [comment]
Solved by PR:
https://github.com/Rocketmakers/armstrong-edge/pull/237
