### ISSUE TITLE
Formprop set doesn't work for string union property types

### ISSUE THREAD

**Issue by adamiprinciples** [Rocketmakers/armstrong-edge#32]
### Expected Behaviour
Should be able to use `formProp('stringUnionField').set('stringUnionValue')`

### Actual Behaviour
Get `Argument of type 'string' is not assignable to parameter of type 'never'`

![image](https://user-images.githubusercontent.com/1008185/126650008-cf8b9244-fb5c-441c-8049-a0fca6202f1c.png)

### Steps to Reproduce
Create a form bound to any object with one of the properties being a string union type, e.g

```
export type ExecutionType = 'scheduled' | 'manual';

export interface IJob {
  id?: string;
  jobName: string;
  vendorConfig: string;
  companyConfig: string;
  customerConfig: string;
  executionType: ExecutionType;
}
```

then just try to manually set the property, for example
```
formProp('executionType').set('scheduled')
```

**Comment by jlews** [comment]
Resolved in PR:
https://github.com/Rocketmakers/armstrong-edge/pull/33
