### ISSUE TITLE
[Dialog Hook] Resolve has implicit any type in dialog hook

### ISSUE THREAD

**Issue by adamiprinciples** [Rocketmakers/armstrong-edge#36]
## Overview

Resolve promise in dialog hooks has implicit any so won't work in projects where this is not allowed.

### Expected Behaviour
The 'resolve' property of the useDialog constructor should be typed as `Promise<T>`  with `T` coming from the first type parameter of the use dialog constructor, e.g `useDialog<boolean>({ resolve ))` where resolve would be `Promise<boolean>`

### Actual Behaviour
![image](https://user-images.githubusercontent.com/1008185/126967483-aaed32e6-f2e7-4bdd-b891-b4759cbe2fd9.png)

### Steps to Reproduce
See above image

**Comment by adamiprinciples** [comment]
This works fine with the `useModal` hook, just not `useDialog`

**Comment by jlews** [comment]
Fixed in #37
