### ISSUE TITLE
useDialog not displaying up to date value from external state

### ISSUE THREAD

**Issue by adamiprinciples** [Rocketmakers/armstrong-edge#40]
### Expected Behaviour
Should be able to pass a value from state into a dialog via the `useDialog` hook

### Actual Behaviour
State value displayed in dialog is always one update behind.

### Steps to Reproduce
```
const [coolGuy,setCoolGuy] = React.useState("Patrick");
const [open] = useDialog<any, any>((p) =><div>{coolGuy}</div>)

 return (<div>
   {coolGuy}
  <Button onClick={() => setCoolGuy(coolGuy === "Patrick" ? "Adam" : "Patrick")}>Toggle guy</Button>
  <Button onClick={open}>Open dialog</Button>
</div>
)
```

Using a simple example like above, clicking the button will toggle the name in state. Opening the dialog you'll see the previous value displayed. Opening it a second time without changing state you'll see the new value.

**Comment by jlews** [comment]
Resolved by tiny PR:
https://github.com/Rocketmakers/armstrong-edge/pull/53
