### ISSUE TITLE
ScrollToEndListener not firing when scrolling to end of the page.

### ISSUE THREAD

**Issue by marcusxavier85** [Rocketmakers/armstrong-edge#64]
## Overview

ScrollToEndListener not firing when scrolling to end of the page.

## Bug report (delete if not a bug report)
ScrollToEndListener not firing when scrolling to end of the page.

### Expected Behaviour
To load additional fetches from the API once scrolled to the bottom of the screen

### Actual Behaviour
Loads the intial fetch but then doesn't load anymore afterwards once scrolled to the bottom

### Steps to Reproduce
```
export const RewardsView: React.FC = () => {
  const totalBiscuits = 45700;

  const { accessToken } = React.useContext(Auth0Context);

  const getRewards = apiHooks(accessToken).rewardClient.rewardsGet.useRequest();

  const fetchItems = React.useCallback(async (pageToken?: PageToken): Promise<IInfinitePagingResult<Reward>> => {
    if (!pageToken) {
      console.log('No page token:', pageToken);

      return { data: [] };
    }
    const { data } = await getRewards({ page: +pageToken, pageSize: 1 });
    console.log('current items', data?.data, 'current page:', pageToken, 'and next page: ', data?.paging?.next);
    return { data: data?.data || [], nextPageToken: data?.paging?.next || 1 };
  }, []);

  const { items, loadMore } = useInfinitePaging<Reward>(fetchItems, (item) => item?.id?.value || '', {
    firstPageToken: 1,
    pageSize: 1,
  });

  return (
    <View title="Rewards" className={styles.rewardsView} unpadded={true}>
      <div className={styles.totalBiscuit}>
        <h3>Total Biscuits</h3>
        <div>
          <img src={BiscuitLogoPurple} />
          {totalBiscuits.toLocaleString()}
        </div>
      </div>
      <div className={styles.totalBiscuit}>
        <h3>Total Biscuits</h3>
        <div>
          <img src={BiscuitLogoPurple} />
          {totalBiscuits.toLocaleString()}
        </div>
      </div>
      <ScrollToEndListener
        onScrollToEnd={async () => {
          console.log('Scrolled to end');
          await loadMore();
        }}
        rootMargin={'77px'}
      >
        {items.map((item) => {
          return (
            <RewardCard
              key={item?.id?.value}
              image={BiscuitLogoPurple}
              biscuitValue={item.priority}
              company={item.name}
              value={item.price}
              category={item?.category?.name}
            />
          );
        })}
      </ScrollToEndListener>
    </View>
  );
};

```
## Internal

We use JIRA for issue tracking internally. If you're in Rocketmakers and you have an issue to raise, raise a ticket in [JIRA](https://rocketmakers.atlassian.net/jira/software/projects/HM/boards/172) and notify the `#armstrong` Slack channel.

**Comment by patrickbenjamin1** [comment]
I've raised a merge request with what I think might be a fix

There was a missing dependency on a useCallback in a hook that _could_ be the problem, but I'm not 100% sure (largely cus I remember at the time not being able to reproduce the problem in a playground, but there could've been something else going on there)

Would be good to test this fix in the repo the issue came up in though, can it be updated in the package json to point to this commit then tested with the updated ScrollToEndListener?

```json
{
   "dependencies":  {
      "@rocketmakers/armstrong-edge": "git://github.com/rocketmakers/armstrong-edge/#f4d7c1b7ec1cf62118f03c9884ecf264310fcf75"
   }
}
```
^ i think that'll do it

**Comment by patrickbenjamin1** [comment]
Once the fix is in and deployed, we should revert that, though
